sudo: false
language: rust
rust:
- nightly
- beta
- stable
before_script:
- ! 'pip install ''travis-cargo<0.2'' --user

'
script:
- ! 'cargo build &&

  cargo test &&

  travis-cargo --only stable doc -- &&

  cargo build --no-default-features

'
after_success:
- ! 'travis-cargo --only stable doc-upload

'
deploy:
  provider: releases
env:
  global:
  - secure: VbLfHRPv/jTnGWiUjwK/s9AmHvNH6cEUcUjJP8kv8OLwkLhfykZS+kjHPH1PsKC2MU26PJ6jHRGX+zMuvYxLzZ87F1cC6x+afkvTfNlCEWqbSmZ2g51zxh9iX1rDeLQsi6EPcDedl1Q+DblacKLSB25kd8bGCKaZUAjG2E0qXT0W4eeWXRHu4izZYGscRTWElI03BGq4bvu6V92XlPekFi4gdQzs5cbIUnV0XMLE5IXF7Rv5Ln67QY6HQ2paX25qBNzgRmnwn+Ozwzq3IJl1JvK7hP6UTgB7RyUH7vJykE81jrCJn3uL68GjO9Cu22IJb7MKhF3rVOOUatxoqj45CyveOSzwbP/X/SmZUjeN21jP8/fveVVODo0bJInmrLoh0oAi7VkS9tOXXhB2w5nHxDDFAKrU+7rOBvpMx+Pwby42qWsC3pTCPxnT8KeQv6FLRVqdcG+AHYTAlzC7UVF0RUlHmJrDl4CT5V0thmlVoi693WlxVsFkrQFeWcoMFqZzoiEdcB7BYW6Q3NoyXP13KKUfLXSz+l/7FBlBw7fPrEUGhNrKt6CV/6CkKj8MJBXe62myxZ+zBrTIpI9LHCAuQ2V5t3fwyAbPoM0Cz2mQ0UXcmolUSVTlSHOoW29Bwev9GTJTlzsydbmOuPQKucIWzYIkqT46mWiqekn8EnTUrZ8=
  - secure: EiR4+bRBUEDcC9JWnnmrudRO2y6uuYAVCCL72jBhy1wq88wuFnRXV7Mk9mLiynnE5DdRFUM9wjzGzO/sw1dWyeuSsPZSErTjXqeX3Hyk4wHTB6pRZYeTjchmmvAZVzJymx/CaBLGl415i3d+atq2z9B4UmYTHGyC7CHMKA5uRPn/dn+TMnkf77VXr942v+xXMZqVR133mUcOPlQ9vz4RwYqu+vjkFpO+YWkapxU3OMdhJVcchDy/izrtg+bZ2k8+M3iWukyElzd29nSulT+YXSWVLcUhngSlYQgSQzdooC4di11Qra+wzWYkzpVJLtYfH7AsNl17n3OeRJoknWwalJjhjz/Rt05vx0AGK5b2409kPhNxPNXnwaKP3+EP4UKzOA5m4F60eaSxs+6Qz8YOUJourEiCLqRWHHmV0pUFPLwitrUNP2uDHgo9RqCLbe2G2JBwmE3Q2XvDwqd/dYhXbOF4LmpC9S1eDWQYdugnTKoTPsBcYMD4nC5fvDue+rCW3F21ZrDF5P8G8T/9a3D+kK7UnGWTmNf92I0M6ORjI3G63KDLNa2m02yDcQoFPXA9Fj5ektM0jYZEoLCF2nlsY1MfAW4qnko0eO+G3ecdESrLUGV111MPIarztW9GiNiDegMEfrv9wq1CEG7C9vM0Wrj0gcJtmRfiuRm+cAzINvo=
