[package]
name = "unqlite-sys"
version = "0.1.0"
authors = ["Huo Linhe <huolinhe@berrygenomics.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.4"

[build-dependencies]
gcc = "0.3.21"
pkg-config = "0.3.6"

